# Generated by Django 3.1.1 on 2020-09-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='addresh',
            new_name='address',
        ),
    ]
